function [] = concatenate_voxel_based_hurst_exponent(subject)

% The goal of this script is to concatenate all hurst exponent parts files
% that were generated by the compute_voxel_based_hurst_exponent.m script

% Requirements:
% 1. The script compute_voxel_based_hurst_exponent.m has been run.
%
% Input:
% 1. subject -> Subject ID
%
% Output:
% 1 csv files containing the Hurst exponent corresponding to each designated 
% subject's cortical voxel.
%
% Author: Panagiotis Fotiadis, 2021-2023
%
% If parts of the following code are used, please cite the following paper:
%
% Fotiadis P, Cieslak M, He X, Caciagli L, Ouellet M, Satterthwaite TD, 
% Shinohara RT, and Bassett DS “Myelination and excitation-inhibition 
% balance synergistically shape structure-function coupling across the 
% human cortex,” (2023) Nature Communications.

% -------------------------------------------------------------------------

% Initialize variable
concatenated_data = [];

% Load the files
for part = 1:20
    data{part} = load(fullfile('/cbica/home/panosf/Q7/structure_function_coupling',subject,string(subject)+'_voxel_based_ei_hurst_results_part_'+string(part)+'.csv'));
    
    % concatenate them incrementally
    concatenated_data = [concatenated_data; data{part}];
end

% Save the file
writematrix(concatenated_data,fullfile('/cbica/home/panosf/Q7/structure_function_coupling',subject,string(subject)+'_voxel_based_ei_hurst_results.csv'));
